### ISSUE TITLE
new resource creation problem

### ISSUE THREAD

**Issue by konstantino** [projectcs13/sensor-cloud#145] opened 2013-11-19 14:29 UTC
curl -XPOST '193.234.217.160:8000/resources' -H "Content-type: application/json" -d '{"user_id":"4WlKN3g-TJGA5bzP-OQc6g","name":"Temperature0","tags":"Temperature, Celsius","description":"Brand| STMicroelectronics; Model| MBxxx (STM32W108CC); Type| Temp Sensor; Mac| 00:80:e1:03:00:01:38:29; Short Range Radio| 802.15.4; unit| C","type":"Temperature","location":"60.166322,24.943529","active":"true","creation_date":"2013-11-19","uuid":"280:e103:1:3829_Temperature0"}'
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request:<br><pre>{error,
    {error,
        {badmatch,
            [{"{\"user_id\":\"4WlKN3g-TJGA5bzP-OQc6g\",\"name\":\"Temperature0\",\"tags\":\"Temperature, Celsius\",\"description\":\"Brand| STMicroelectronics",
              []},
             {" Model| MBxxx (STM32W108CC)",[]},
             {" Type| Temp Sensor",[]},
             {" Mac| 00:80:e1:03:00:01:38:29",[]},
             {" Short Range Radio| 802.15.4",[]},
             {" unit| C\",\"type\":\"Temperature\",\"location\":\"60.166322,24.943529\",\"active\":\"true\",\"creation_date\":\"2013-11-19\",\"uuid\":\"280:e103:1:3829_Temperature0\"}",
              []}]},
        [{api_help,json_handler,2,[{file,"src/api_help.erl"},{line,93}]},
         {resource,process_post,2,[{file,"src/resource.erl"},{line,165}]},
         {webmachine_resource,resource_call,3,
             [{file,"src/webmachine_resource.erl"},{line,186}]},
         {webmachine_resource,do,3,
             [{file,"src/webmachine_resource.erl"},{line,142}]},
         {webmachine_decision_core,resource_call,1,
             [{file,"src/webmachine_decision_core.erl"},{line,48}]},
         {webmachine_decision_core,decision,1,
             [{file,"src/webmachine_decision_core.erl"},{line,486}]},
         {webmachine_decision_core,handle_request,2,
             [{file,"src/webmachine_decision_core.erl"},{line,33}]},
         {webmachine_mochiweb,loop,2,
             [{file,"src/webmachine_mochiweb.erl"},{line,74}]}]}}</pre><P><HR><ADDRESS>mochiweb+webmachine web server</ADDRESS></body></html>

**Comment by tosa7943** [comment] 2013-11-19 14:38
I will look into it, my first guess is that ; in the description is causing some errors, but I will check it and try to fix it

**Comment by konstantino** [comment] 2013-11-19 14:40
Yeap - I had the same feeling, however, technically speaking that character
is not invalid from a JSON payload point of view. Anyhow it's not that
urgent, I've already asked the colleague working on it to avoid abusing the
description field that heavily and just to push ad-hoc new attributes into
the system with each field separately instead.

**Comment by tosa7943** [comment] 2013-11-19 15:18
Problem was caused by a function that we didn't need to use so I changed it to use another function that don't give this problem. It should be fixed in develop as soon as my pull request is merged

**Comment by tosa7943** [comment] 2013-11-19 15:20
See pull request #147 for solution

**Comment by konstantino** [comment] 2013-11-19 15:21
Can you describe where the change happened? This particular installation is
going to be used for a demonstration and it is a couple of weeks old. Since
the current setup has already passed most tests I would prefer to avoid
starting the testing process all over, but instead just fix this minor
issue. Let me know if that is possible.

**Closed as completed by tosa7943** 2013-11-19 15:20 UTC

**Comment by tosa7943** [comment] 2013-11-19 15:24
Sure, as you can see in the pullrequest the change is in api_help.erl, 
[{Value,_ }] = mochiweb_util:parse_qs(wrq:req_body(ReqData)),
on line 148 was changed to
Value = binary_to_list(wrq:req_body(ReqData)),
